service:
  name: orcas-serverless
custom:
  secrets: ${file(secrets.json)}
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  profile: orcas-serverless-admin
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    API_CHIMP_KEY: ${self:custom.secrets.API_CHIMP_KEY}
    DATA_CENTER: ${self:custom.secrets.DATA_CENTER}
    LIST_ID: ${self:custom.secrets.LIST_ID}
functions:
  subscribe:
    handler: src/handler.run
    events:
      - http:
          path: /
          method: post
          cors: true